In [4]:
import pandas as pd

raw_df = pd.read_csv("/Users/sngirish/personal_work/mtech-learning/data-science/project/Media-Bias-Analysis-in-Indian-News-Articles/articles/raw/indian_express_article_content_2024_progress_50.csv")

In [5]:
raw_df.head()

,success,url,title,author,published_date,modified_date,section,tags,article_text,word_count,error,media_name,scrape_date,csv_index
0,True,https://indianexpress.com/article/cities/pune/...,"Pune activists, citizens demand clarity on ame...","Shubham TiggaPune |Updated: January 2, 2024 09...",2024-01-02T09:03:17+05:30,2024-01-02T09:03:17+05:30,NaN,NaN,Introduction of the new Bharatiya Nyay Sanhita...,510,NaN,THE INDIAN EXPRESS,2024-01-01,0
1,True,https://indianexpress.com/article/cities/mumba...,Ram Mandir inauguration: Govt should declare J...,:Express News ServiceMumbai |Updated: January ...,2024-01-02T04:47:54+05:30,2024-01-02T04:47:54+05:30,NaN,NaN,BJP leader Atul Bhatkhalkar on Monday wrote a ...,165,NaN,THE INDIAN EXPRESS,2024-01-01,1
2,True,https://indianexpress.com/article/cities/chenn...,PM Modi to visit TN tomorrow to inaugurate new...,":Express Web DeskChennai |Updated: January 2, ...",2024-01-02T09:13:45+05:30,2024-01-02T09:13:45+05:30,NaN,NaN,Prime Minister Narendra Modi is slated to visi...,539,NaN,THE INDIAN EXPRESS,2024-01-01,2
3,True,https://indianexpress.com/article/cities/mumba...,894 total Covid cases registered in Maharashtr...,"Rupsa ChakrabortyMumbai |Updated: January 2, 2...",2024-01-02T04:47:40+05:30,2024-01-02T04:47:40+05:30,NaN,NaN,Maharashtra registered a total of 894 new COVI...,296,NaN,THE INDIAN EXPRESS,2024-01-01,3
4,True,https://indianexpress.com/article/cities/mumba...,Thane Rave Party: Two arrested organisers rema...,:Express News ServiceMumbai |Updated: January ...,2024-01-02T04:49:41+05:30,2024-01-02T04:49:41+05:30,NaN,NaN,Two persons who were arrested early on Sunday ...,264,NaN,THE INDIAN EXPRESS,2024-01-01,4

In [7]:

cat_df = pd.read_csv("/Users/sngirish/personal_work/mtech-learning/data-science/project/Media-Bias-Analysis-in-Indian-News-Articles/articles/cat/indian_express_article_content_2024_progress_50_cat.csv")

In [8]:
cat_df.head()

,text,url,title,published_date,media_name,csv_index,processed_text,keyword_topic,keyword_confidence
0,Introduction of the new Bharatiya Nyay Sanhita...,https://indianexpress.com/article/cities/pune/...,"Pune activists, citizens demand clarity on ame...",2024-01-02T09:03:17+05:30,THE INDIAN EXPRESS,0,introduction new bharatiya nyay sanhita bns cl...,politics,0.125000
1,BJP leader Atul Bhatkhalkar on Monday wrote a ...,https://indianexpress.com/article/cities/mumba...,Ram Mandir inauguration: Govt should declare J...,2024-01-02T04:47:54+05:30,THE INDIAN EXPRESS,1,bjp leader atul bhatkhalkar monday wrote lette...,politics,0.250000
2,Prime Minister Narendra Modi is slated to visi...,https://indianexpress.com/article/cities/chenn...,PM Modi to visit TN tomorrow to inaugurate new...,2024-01-02T09:13:45+05:30,THE INDIAN EXPRESS,2,prime minister narendra modi slated visit tami...,infrastructure,0.666667
3,Maharashtra registered a total of 894 new COVI...,https://indianexpress.com/article/cities/mumba...,894 total Covid cases registered in Maharashtr...,2024-01-02T04:47:40+05:30,THE INDIAN EXPRESS,3,maharashtra registered total new covid cases d...,health,0.714286
4,Two persons who were arrested early on Sunday ...,https://indianexpress.com/article/cities/mumba...,Thane Rave Party: Two arrested organisers rema...,2024-01-02T04:49:41+05:30,THE INDIAN EXPRESS,4,persons arrested early sunday morning organisi...,unknown,0.000000

In [15]:
import pandas as pd

biased_df = pd.read_csv("./articles/bias/indian_express_article_content_2024_progress_1000_cat_bias_analysis.csv")

In [16]:
biased_df.head(100)

,text,url,title,published_date,media_name,csv_index,processed_text,keyword_topic,keyword_confidence,bias_score,bias_label,model_used,model_type,raw_prediction,processed_text_length,bias_category
0,Introduction of the new Bharatiya Nyay Sanhita...,https://indianexpress.com/article/cities/pune/...,"Pune activists, citizens demand clarity on ame...",2024-01-02T09:03:17+05:30,THE INDIAN EXPRESS,0,introduction new bharatiya nyay sanhita bns cl...,politics,0.125000,0.227076,neutral,cardiffnlp/twitter-roberta-base-sentiment-latest,sentiment,"{'label': 'neutral', 'score': 0.7569207549095154}",5,low_bias
1,BJP leader Atul Bhatkhalkar on Monday wrote a ...,https://indianexpress.com/article/cities/mumba...,Ram Mandir inauguration: Govt should declare J...,2024-01-02T04:47:54+05:30,THE INDIAN EXPRESS,1,bjp leader atul bhatkhalkar monday wrote lette...,politics,0.250000,0.255379,neutral,cardiffnlp/twitter-roberta-base-sentiment-latest,sentiment,"{'label': 'neutral', 'score': 0.8512619137763977}",5,low_bias
2,Prime Minister Narendra Modi is slated to visi...,https://indianexpress.com/article/cities/chenn...,PM Modi to visit TN tomorrow to inaugurate new...,2024-01-02T09:13:45+05:30,THE INDIAN EXPRESS,2,prime minister narendra modi slated visit tami...,infrastructure,0.666667,0.162832,neutral,cardiffnlp/twitter-roberta-base-sentiment-latest,sentiment,"{'label': 'positive', 'score': 0.5427742600440...",5,low_bias
3,Maharashtra registered a total of 894 new COVI...,https://indianexpress.com/article/cities/mumba...,894 total Covid cases registered in Maharashtr...,2024-01-02T04:47:40+05:30,THE INDIAN EXPRESS,3,maharashtra registered total new covid cases d...,health,0.714286,0.268052,neutral,cardiffnlp/twitter-roberta-base-sentiment-latest,sentiment,"{'label': 'neutral', 'score': 0.8935065865516663}",5,low_bias
4,Two persons who were arrested early on Sunday ...,https://indianexpress.com/article/cities/mumba...,Thane Rave Party: Two arrested organisers rema...,2024-01-02T04:49:41+05:30,THE INDIAN EXPRESS,4,persons arrested early sunday morning organisi...,unknown,0.000000,0.246214,neutral,cardiffnlp/twitter-roberta-base-sentiment-latest,sentiment,"{'label': 'neutral', 'score': 0.8207129240036011}",5,low_bias
5,Veteran BJP leader and former Karnataka chief ...,https://indianexpress.com/article/cities/banga...,Ram Lalla idol made by Karnataka’s Arun Yogira...,2024-01-02T10:25:04+05:30,THE INDIAN EXPRESS,5,veteran bjp leader karnataka chief minister ye...,politics,0.125000,0.231117,neutral,cardiffnlp/twitter-roberta-base-sentiment-latest,sentiment,"{'label': 'neutral', 'score': 0.7703902125358582}",5,low_bias
6,As many as 816 motorists were booked by the po...,https://indianexpress.com/article/cities/mumba...,"Mumbai, Thane & Navi Mumbai: 816 motorists boo...",2024-01-02T04:57:18+05:30,THE INDIAN EXPRESS,6,motorists booked police driving influence mumb...,unknown,0.000000,0.260625,neutral,cardiffnlp/twitter-roberta-base-sentiment-latest,sentiment,"{'label': 'neutral', 'score': 0.868751585483551}",5,low_bias
7,"Four people, including the contractor, behind ...",https://indianexpress.com/article/cities/ahmed...,"4 labourers arrested, 1 juvenile detained in B...",2024-01-02T09:08:45+05:30,THE INDIAN EXPRESS,7,people including contractor alleged theft gold...,sports,0.125000,0.279570,neutral,cardiffnlp/twitter-roberta-base-sentiment-latest,sentiment,"{'label': 'neutral', 'score': 0.9319003224372864}",5,low_bias
8,The Manipur government imposed curfew across t...,https://indianexpress.com/article/india/manipu...,"4 shot dead in Manipur’s valley district, curf...",2024-01-02T09:44:09+05:30,THE INDIAN EXPRESS,8,manipur government imposed curfew state valley...,politics,0.250000,0.160626,neutral,cardiffnlp/twitter-roberta-base-sentiment-latest,sentiment,"{'label': 'neutral', 'score': 0.5354186296463013}",5,low_bias
9,Three people were killed and six others injure...,https://indianexpress.com/article/north-east-i...,Two-wheeler accidents kill 3 people and injure...,2024-01-01T21:20:47+05:30,THE INDIAN EXPRESS,9,people killed injured road accidents tripura n...,unknown,0.000000,0.626604,potential_bias,cardiffnlp/twitter-roberta-base-sentiment-latest,sentiment,"{'label': 'negative', 'score': 0.8951480388641...",5,high_bias